#!/usr/bin/env node --experimental-strip-types
/**
 * scripts/build-i18n.ts
 *
 * Reads every locale JSON file from src/i18n/locales/ and writes
 * src/i18n/locales.ts, which exports each locale as a typed TypeScript const
 * using the Locale interface from src/i18n/index.ts.
 *
 * Usage:
 *   node --experimental-strip-types scripts/build-i18n.ts
 */

import {readFileSync, writeFileSync, mkdirSync, readdirSync} from "fs"
import {join, basename, dirname} from "path"
import {fileURLToPath} from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = join(__dirname, "..")
const localesDir = join(rootDir, "src", "i18n", "locales")
const outDir = join(rootDir, "src", "i18n")
const outFile = join(outDir, "locales.ts")

// ---------------------------------------------------------------------------
// Read locale files
// ---------------------------------------------------------------------------

interface LocaleEntry {
    tag: string
    id: string
    data: Record<string, unknown>
}

const localeFiles = readdirSync(localesDir)
    .filter((f: string) => f.endsWith(".json"))
    .sort()

if (localeFiles.length === 0) {
    console.error(`No JSON files found in ${localesDir}`)
    process.exit(1)
}

/**
 * Derive a safe TypeScript identifier from an IETF language tag.
 * e.g. "pt-BR" → "ptBR", "en" → "en"
 */
function tagToIdentifier(tag: string): string {
    return tag.replace(/-([a-zA-Z])/g, (_, c: string) => c.toUpperCase())
}

const locales: LocaleEntry[] = localeFiles.map((file: string) => {
    const tag = basename(file, ".json")
    const id = tagToIdentifier(tag)
    const data = JSON.parse(readFileSync(join(localesDir, file), "utf8")) as Record<string, unknown>
    return {tag, id, data}
})

// ---------------------------------------------------------------------------
// Code generation helpers
// ---------------------------------------------------------------------------

/**
 * Serialise a plain JSON value to a TypeScript literal. We intentionally avoid
 * JSON.stringify so we get readable output with keys quoted only when they
 * contain non-identifier characters (e.g. "article-journal").
 */
function serializeValue(value: unknown, indent: string): string {
    if (typeof value === "string") {
        // Escape backslashes and double-quotes, keep everything else as-is.
        const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')
        return `"${escaped}"`
    }
    if (Array.isArray(value)) {
        if (value.length === 0) return "[]"
        const inner = value
            .map((v: unknown) => `${indent}    ${serializeValue(v, indent + "    ")}`)
            .join(",\n")
        return `[\n${inner},\n${indent}]`
    }
    if (value !== null && typeof value === "object") {
        const entries = Object.entries(value as Record<string, unknown>)
        if (entries.length === 0) return "{}"
        const inner = entries
            .map(([k, v]) => {
                // Use a quoted key if the key contains non-identifier chars.
                const needsQuotes = !/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k)
                const keyStr = needsQuotes ? `"${k}"` : k
                return `${indent}    ${keyStr}: ${serializeValue(v, indent + "    ")}`
            })
            .join(",\n")
        return `{\n${inner},\n${indent}}`
    }
    // number, boolean, null
    return String(value)
}

/** Render a single typed locale export const declaration. */
function renderLocaleConst({id, tag, data}: LocaleEntry): string {
    return `// Locale: ${tag}\nexport const ${id}: Locale = ${serializeValue(data, "")}\n`
}

// ---------------------------------------------------------------------------
// Assemble output
// ---------------------------------------------------------------------------

const banner = `\
// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by: scripts/build-i18n.ts
// Source files: src/i18n/locales/*.json
//
// To regenerate:
//   npm run compile_i18n

import type {Locale} from "./index.ts"

`

const output = [
    banner,
    locales.map(renderLocaleConst).join("\n"),
].join("")

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------

mkdirSync(outDir, {recursive: true})
writeFileSync(outFile, output, "utf8")

console.log(
    `src/i18n/locales.ts written (${locales.length} locale${locales.length === 1 ? "" : "s"}: ${locales.map((l) => l.tag).join(", ")})`,
)