name: Test CI

on:
    push:
        branches-ignore:
            - gh-pages
            - browser
    pull_request:
        branches:
            - "*"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
            - run: |
                  npm install
                  npm test
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract Branch Name
              run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
            - name: Deploy gh-pages branch
              if: env.BRANCH == 'main'
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: gh-pages
                  build_dir: gh-pages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Deploy browser branch
              if: env.BRANCH == 'main'
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: browser
                  build_dir: browser
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
